model: SoundStreamInversion
model_key: ssinv
model_params:
  in_channels: 1
  out_channels: 14
  kernel_size: 7
  strides: [2, 5, 6, 8]
  dilations: [1, 3, 9]

discriminator: MelGANMultiScaleDiscriminator
discriminator_params:
  in_channels: 14
  out_channels: 1

###################################
#              DATASET            #
###################################
dataset: LibriTTSRDataset
dataset_params:
  data_path: /data/common/LibriTTS_R

###################################
#           DATALOADER            #
###################################
dataloader_params:
  batch_size: 1
  shuffle: True

###################################
#              TRAINING           #
###################################
seed: 0
epochs: 30
train_split: 0.8
val_split: 0.1

###################################
#              OPTIM              #
###################################
optim_params:
  lr: 1.0e-4
  betas: [0.5, 0.9]
  weight_decay: 0.0

sched_params:
  gamma: 0.5
  milestones: [40000, 80000, 120000, 160000]

###################################
#              LOSS               #
###################################
loss: l1
gen_adv: gen_adv
disc_adv: disc_adv
